# Generated by Django 2.2.4 on 2019-08-15 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='autor',
            new_name='autor',
        ),
    ]
